language: cpp
compiler: gcc
dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo apt-get install doxygen graphviz
script:
  - cd test
  - cmake -H. -Bcmake
  - cmake --build cmake
  - cmake --build cmake --target test
  - cd ..
  - doxygen Doxyfile
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: html
    on:
      branch: master
